name: roboclub_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+9

environment:
  sdk: ">=2.12.0 <3.16.1"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  #Store data in device
  shared_preferences: ^2.0.7
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  google_sign_in: ^6.1.5
  firebase_messaging: ^14.6.9

  flutter_svg: ^2.0.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  url_launcher: ^6.0.10
  google_fonts: ^4.0.4
  youtube_player_flutter: ^8.0.0
  google_maps_flutter: ^2.0.9
  location: ^5.0.3
  intl: ^0.18.1
  date_format: ^2.0.4
  file_picker: ^6.0.0
  firebase_storage: ^11.2.8
  firebase_core: ^2.17.0
  http: ^0.13.3
  flutter_dotenv: ^5.0.2
  carousel_slider: ^4.0.0
  percent_indicator: ^4.2.2
  cached_network_image: ^3.2.0
  device_info_plus: ^9.0.3
  sendgrid_mailer: 
  firebase_remote_config: ^4.3.4
  skeleton_loader: ^2.0.0+4
  fluttertoast: ^8.0.8
  package_info_plus: ^4.1.0
  razorpay_flutter: ^1.3.3
  crypto: ^3.0.1
  string_encryption: ^2.0.3
  pdf: ^3.6.5
  path_provider: ^2.0.8
  progress_dialog_null_safe: ^1.0.7
  # in_app_update: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/illustrations/
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: MyFlutterApp
      fonts:
        - asset: assets/icons/MyFlutterApp.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    - family: SocialMedia
      fonts:
        - asset: assets/icons/SocialMedia.ttf

    - family: Report
      fonts:
        - asset: assets/icons/Report.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
